dove_mail_app/config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('mail', include("core_app.urls", namespace='core_app')),
    path('user', include('user_app.urls', namespace='user_app')),
]

dove_mail_app/core_app/urls.py
from django.urls import path
from .views import MailingListView, CreateMailingListView, DeleteMailingListView, MailingListDetailView, \
    SubscribeToMailingListView, ThankYouForSubscribingView, ConfirmSubscriptionView, UnsubscribeView, \
    CreateMessageView, MessageDetailView

app_name = "core_app"

urlpatterns = [
    path('', MailingListView.as_view(), name='mailing_list'),
    path('new', CreateMailingListView.as_view(), name='create_mailinglist'),
    path('<uuid:pk>/delete', DeleteMailingListView.as_view(), name='delete_mailinglist'),
    path('<uuid:pk>/manage', MailingListDetailView.as_view(), name='manage_mailinglist'),
    path('<uuid:pk>/subscribe', SubscribeToMailingListView.as_view(), name='subscribe'),
    path('<uuid:pk>/thankyou', ThankYouForSubscribingView.as_view(), name='subscriber_thankyou'),
    path('subscribe/confirmed/<uuid:pk>', ConfirmSubscriptionView.as_view(), name='confirm_subscription'),
    path('unsubscribe/<uuid:pk>', UnsubscribeView.as_view(), name='unsubscribe'),
    path('<uuid:mailinglist_pk>/message/new', CreateMessageView.as_view(), name='create_message'),
    path('message/<uuid:pk>', MessageDetailView.as_view(), name="view_message")
]

dove_mail_app/core_app/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse

import uuid
from . import emails, tasks

# Create your models here.


class MailingList(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=140)
    owner = models.ForeignKey(to=settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse(
            'core_app:manage_mailinglist',
            kwargs={'pk', self.id}
        )

    def user_can_use_mailing_list(self, user):
        return user == self.owner


class SubscriberManager(models.Manager):

    def confirmed_subscribers_for_mailing_list(self, mailing_list):
        qs = self.get_queryset()
        qs = qs.filter(confirmed=True)
        qs = qs.filter(mailing_list=mailing_list)
        return qs


class Subscriber(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    email = models.EmailField()
    confirmed = models.BooleanField(default=False)
    mailing_list = models.ForeignKey(to=MailingList, on_delete=models.CASCADE)

    class Meta:
        unique_together = ['email', 'mailing_list']

    def save(self, force_insert=False, force_update=False, using=None,
             update_fields=None):
        is_new = self._state.adding or force_insert
        super().save(force_insert=force_insert, force_update=force_update, using=using, update_fields=update_fields)
        if is_new:
            self.send_confirmation_email()

    def send_confirmation_email(self):
        tasks.send_confirmation_email_to_subscriber.delay(self.id)

    objects = SubscriberManager()


class Message(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    mailing_list = models.ForeignKey(to=MailingList, on_delete=models.CASCADE)
    subject = models.CharField(max_length=140)
    body = models.TextField()
    started = models.DateTimeField(default=None, null=True)
    finished = models.DateTimeField(default=None, null=True)


class SubscriberMessageManager(models.Manager):

    def create_from_message(self, message):
        confirmed_subs = Subscriber.objects.confirmed_subscribers_for_mailing_list(message.mailing_list)
        return [self.create(message=message, subscriber=subscriber) for subscriber in confirmed_subs]


class SubscriberMessage(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    message = models.ForeignKey(to=Message, on_delete=models.CASCADE)
    subscriber = models.ForeignKey(to=Subscriber, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    sent = models.DateTimeField(default=None, null=True)
    last_attempt = models.DateTimeField(default=None, null=True)

    objects = SubscriberMessageManager()

    def save(self, force_insert=False, force_update=False, using=None, update_fields=None):
        is_new = self._state.adding or force_insert
        super().save(force_insert=force_insert, force_update=force_update, using=using, update_fields=update_fields)
        if is_new:
            self.send()

        def send(self):
            tasks.send_subscriber_message.delay(self.id)

dove_mail_app/core_app/forms.py
from django import forms
from django.contrib.auth import get_user_model

from .models import MailingList, Subscriber, Message


class SubscriberForm(forms.ModelForm):
    mailing_list = forms.ModelChoiceField(widget=forms.HiddenInput, queryset=MailingList.objects.all(), disabled=True)

    class Meta:
        model = Subscriber
        fields = ['mailing_list', 'email']


class MessageForm(forms.ModelForm):
    mailing_list = forms.ModelChoiceField(widget=forms.HiddenInput, queryset=MailingList.objects.all(), disabled=True)

    class Meta:
        model = Message
        fields = ['mailing_list', 'subject', 'body']


class MailingListForm(forms.ModelForm):
    owner = forms.ModelChoiceField(widget=forms.HiddenInput, queryset=get_user_model().objects.all(), disabled=True)

    class Meta:
        model = MailingList
        fields = ['owner', 'name']

dove_mail_app/core_app/views.py
from django.shortcuts import get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView, CreateView, DeleteView, DetailView
from django.urls import reverse_lazy, reverse
from django.core.exceptions import PermissionDenied

from .mixins import UserCanUseMailingList
from .models import MailingList, Subscriber, Message
from .forms import MailingListForm, SubscriberForm, MessageForm

# Create your views here.


class MailingListView(LoginRequiredMixin, ListView):

    template_name = 'mailing_list.html'
    context_object_name = 'mailing_list'

    def get_queryset(self):
        return MailingList.objects.filter(owner=self.request.user)


class CreateMailingListView(LoginRequiredMixin, CreateView):
    form_class = MailingListForm
    template_name = 'mailinglist_form.html'

    def get_initial(self):
        return {'owner': self.request.id}


class DeleteMailingListView(LoginRequiredMixin, UserCanUseMailingList, DeleteView):
    model = MailingList
    success_url = reverse_lazy('core_app:mailing_list')


class MailingListDetailView(LoginRequiredMixin, UserCanUseMailingList, DetailView):
    model = MailingList
    template_name = 'mailinglist_detail.html'


class SubscribeToMailingListView(CreateView):
    form_class = SubscriberForm
    template_name = 'subscriber_form.html'

    def get_initial(self):
        return {'mailing_list': self.kwargs['mailinglist_id']}

    def get_success_url(self):
        return reverse('core_app:subscriber_thankyou', kwargs={'pk': self.object.mailing_list.id})

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        mailing_list_id = self.kwargs['mailinglist_id']
        context['mailing_list'] = get_object_or_404(MailingList, id=mailing_list_id)
        return context


class ThankYouForSubscribingView(DetailView):
    model = MailingList
    template_name = 'subscription_thankyou.html'


class ConfirmSubscriptionView(DetailView):
    model = Subscriber
    template_name = 'confirm_subscription.html'

    def get_object(self, queryset=None):
        subscriber = super().get_object(queryset=queryset)
        subscriber.confirmed = True
        subscriber.save()
        return subscriber


class UnsubscribeView(DeleteView):
    model = Subscriber
    template_name = 'unsubscribe.html'

    def get_success_url(self):
        mailing_list = self.object.mailing_list
        return reverse('core_app:subscribe', kwargs={'mailinglist_pk': mailing_list.id})


class CreateMessageView(LoginRequiredMixin, CreateView):
    SAVE_ACTION = 'save'
    PREVIEW_ACTION = 'preview'

    form_class = MessageForm
    template_name = 'message_form.html'

    def get_success_url(self):
        return reverse('core_app:manage_mailinglist', kwargs={'pk': self.object.mailing_list.id})

    def get_initial(self):
        mailing_list = self.get_mailing_list()
        return {'mailing_list': mailing_list.id}

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        mailing_list = self.get_mailing_list()
        context.update({
            'mailing_list': mailing_list,
            'SAVE_ACTION': self.SAVE_ACTION,
            'PREVIEW_ACTION': self.PREVIEW_ACTION
        })
        return context

    def form_valid(self, form):
        action = self.request.POST.get('action')
        if action == self.PREVIEW_ACTION:
            context = self.get_context_data(
                form=form,
                message=form.instance
            )
            return self.render_to_response(context=context)
        elif action == self.SAVE_ACTION:
            return super().form_valid(form)

    def get_mailing_list(self):
        mailing_list = get_object_or_404(MailingList, id=self.kwargs['mailinglist_pk'])
        if not mailing_list.user_can_use_mailing_list(self.request.user):
            raise PermissionDenied()
        return mailing_list


class MessageDetailView(LoginRequiredMixin, UserCanUseMailingList, DetailView):
    model = Message

dove_mail_app/core_app/templates/confirm_subscription.html
{% extends "base.html" %}

{% block title %}
    Subscription to {{subscriber.mailing_list}} confirmed.
{% endblock title %}

{% block body %}
    <h1>Subscription to {{subscriber.mailing_list}} confirmed!</h1>
{% endblock body %}

dove_mail_app/core_app/templates/mailing_list.html
{% extends "base.html" %}

{% block title %}
    Your Mailing Lists
{% endblock title %}

{% block body %}
    <h1>Your Mailing Lists</h1>
    <div>
        <a href="{% url 'core_app:create_mailinglist' %}">New List</a>
    </div>
    <p>Your mailing lists:</p>
    <ul>
        {% for mails in mailing_list %}
            <li>
                <a href="{% url 'core_app:manage_mailinglist' pk=mailinglist.id %}">{{mailinglist.name}}</a>
            </li>
        {% endfor %}
    </ul>
{% endblock body %}

dove_mail_app/core_app/templates/mailinglist_confirm_delete.html
{% extends "base.html" %}

{% block title %}
    Confirm delete {{mailinglist.name}}
{% endblock title %}

{% block body %}
    <h1>Confirm Delete?</h1>
<form action="" method="post">{% csrf_token %}
    <p>Are you sure you want to delete {{mailinglist.name}}?</p>
    <input type="submit" value="Yes">
    <a href="{% url 'core_app:manage_mailinglist' pk=mailinglist.id %}">No</a>
</form>
{% endblock body %}

dove_mail_app/core_app/templates/mailinglist_detail.html
{% extends "base.html" %}

{% block titel %}
    {{mailinglist.name}} Management
{% endblock title %}

{% block body %}
    <h1>{{mailinglist.name}} Management</h1>
    <a href="{% url 'core_app:delete_mailinglist' pk=mailinglist.id %}">Delete</a>

    <div>
        <a href="{% url 'core_app:create_subscriber' pk=mailinglist.pk %}">Subscription Link</a>
    </div>

    <h2>Messages</h2>
    <div>
        <a href="{% url 'core_app:create_message' pk=mailinglist.id %}">Send new Message</a>
    </div>

    <ul>
        {% for message in mailinglist.message_set.all %}
            <li>
                <a href="{% url 'core_app:view_message' pk=message.id %}">{{message.subject}}</a>
            </li>
        {% endfor %}
    </ul>

    <h2>Subscribers</h2>
    <ul>
        {% for subscriber in mailinglist.subscriber_set.all %}
            <li>
                {{subscriber.email}}
                {{subscriber.confirmed|yesno:"confirmed, unconfirmed"}}
                <a href="{% url 'core_app:unsubscribe' pk=subscriber.id %}">Unsubscribe</a>
            </li>
        {% endfor %}
    </ul>
{% endblock body %}

dove_mail_app/core_app/templates/mailinglist_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}
    Create Mailing List
{% endblock title %}

{% block body %}
    <h1>Create Mailing List</h1>
    <form method="post">{% csrf_token %}
        {{form | crispy}}
        <button type="submit">Submit</button>
    </form>
{% endblock %}

dove_mail_app/core_app/templates/message_detail.html
{% extends "base.html" %}
{% load markdownify %}

{% block title %}
    {{message.subject}}
{% endblock %}

{% block body %}
    <h1>{{message.subject}}</h1>
    <div>
        {{message.body|markdownify}}
    </div>
{% endblock body %}

dove_mail_app/core_app/templates/message_form.html
{% extends "base.html" %}

{% load crispy_forms_tags %}
{% load markdownify %}

{% block title %}
    Send a message to {{mailing_list}}
{% endblock title %}

{% block body %}
    {% if message %}
        <div>
            Message Preview
        </div>
        <div>
            <h5>{{message.subject}}</h5>
            {{message.body|markdownify}}
        </div>
    {% endif %}

    <form method="post">{% csrf_token %}
        {{form|crispy}}
        <button type="submit" name="action" value="{{SAVE_ACTION}}">Save</button>
        <button type="submit" name="action" value="{{PREVIEW_ACTION}}">Preview</button>
    </form>
{% endblock body %}

dove_mail_app/core_app/templates/subscriber_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}
    <h1>Subscribe to {{mailing_list}}</h1>
<form method="post">{% csrf_token %}
    {{form|crispy}}
    <button type="submit">Submit</button>
</form>
{% endblock title %}

dove_mail_app/core_app/templates/subscription_thankyou.html
{% extends "base.html" %}

{% block title %}
    Thank you for subscribing to {{mailinglist}}
{% endblock title %}

{% block body %}
    <div>
        <h1>Thank you for subscribing to {{mailinglist}}</h1>
        <p>Check your mail for a confirmation email</p>
    </div>
{% endblock body %}

dove_mail_app/core_app/templates/unsubscribe.html
{% extends "base.html" %}

{% block title %}
    Unsubscribe
{% endblock %}

{% block body %}
    <div>
        <form action="" method="post">{% csrf_token %}
            <p>Are you sure you want to unsubscribe from {{subscriber.mailing_list.name}}?</p>
            <input type="submit" value="Yes, I want to unsubscribe">
        </form>
    </div>
{% endblock % }