dove_mail_app/config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('mail', include("core_app.urls", namespace='core_app')),
    path('user', include('user_app.urls', namespace='user_app')),
]

dove_mail_app/core_app/urls.py
from django.urls import path
from .views import MailingListView, CreateMailingListView, DeleteMailingListView, MailingListDetailView, \
    SubscribeToMailingListView, ThankYouForSubscribingView, ConfirmSubscriptionView, UnsubscribeView, \
    CreateMessageView, MessageDetailView

app_name = "core_app"

urlpatterns = [
    path('', MailingListView.as_view(), name='mailing_list'),
    path('new', CreateMailingListView.as_view(), name='create_mailinglist'),
    path('<uuid:pk>/delete', DeleteMailingListView.as_view(), name='delete_mailinglist'),
    path('<uuid:pk>/manage', MailingListDetailView.as_view(), name='manage_mailinglist'),
    path('<uuid:pk>/subscribe', SubscribeToMailingListView.as_view(), name='subscribe'),
    path('<uuid:pk>/thankyou', ThankYouForSubscribingView.as_view(), name='subscriber_thankyou'),
    path('subscribe/confirmed/<uuid:pk>', ConfirmSubscriptionView.as_view(), name='confirm_subscription'),
    path('unsubscribe/<uuid:pk>', UnsubscribeView.as_view(), name='unsubscribe'),
    path('<uuid:mailinglist_pk>/message/new', CreateMessageView.as_view(), name='create_message'),
    path('message/<uuid:pk>', MessageDetailView.as_view(), name="view_message")
]

dove_mail_app/user_app/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from .views import RegisterView

app_name = 'user_app'

urlpatterns = [
    path('login', LoginView.as_view(template_name='user_app/login.html'), name='login'),
    path('logout', LogoutView.as_view(), name='logout'),
    path('register', RegisterView.as_view(), name='register')
]

dove_mail_app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
        {% endblock title %}
    </title>
</head>
<body>
    <div>
        <a href="#">Dove Mail</a>
        <ul>
            <li>
                <a href="{% url 'core_app:mailing_list' %}">Your Mailing Lists</a>
            </li>
            {% if request.user.is_authenticated %}
                <li>
                    <a href="{% url 'user_app:logout' %}">Logout</a>
                </li>
            {% else %}
                <li>
                    <a href="{% url 'user_app:login' %}">Login</a>
                </li>
                <li>
                    <a href="{% url 'user_app:register' %}">Register</a>
                </li>
            {% endif %}
        </ul>
    </div>
    {% block body %}
    {% endblock body %}
</body>
</html>